// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package database

import (
	"database/sql"
	"time"
)

type Half struct {
	ID           int64        `json:"id"`
	MapName      string       `json:"mapName"`
	AttackerTeam string       `json:"attackerTeam"`
	DefenderTeam string       `json:"defenderTeam"`
	CreatedAt    time.Time    `json:"createdAt"`
	UpdatedAt    sql.NullTime `json:"updatedAt"`
}

type Player struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	VirtualID string       `json:"virtualId"`
	CreatedAt time.Time    `json:"createdAt"`
	UpdatedAt sql.NullTime `json:"updatedAt"`
}

type Stat struct {
	ID        int64        `json:"id"`
	PlayerID  int64        `json:"playerId"`
	HalfID    int64        `json:"halfId"`
	Kills     int64        `json:"kills"`
	Deaths    int64        `json:"deaths"`
	Assists   int64        `json:"assists"`
	Score     int64        `json:"score"`
	Winner    sql.NullBool `json:"winner"`
	CreatedAt time.Time    `json:"createdAt"`
	UpdatedAt sql.NullTime `json:"updatedAt"`
}

type Team struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt time.Time    `json:"createdAt"`
	UpdatedAt sql.NullTime `json:"updatedAt"`
}

type Teamplayer struct {
	ID        int64        `json:"id"`
	PlayerID  int64        `json:"playerId"`
	TeamID    int64        `json:"teamId"`
	CreatedAt time.Time    `json:"createdAt"`
	UpdatedAt sql.NullTime `json:"updatedAt"`
}

type Tournament struct {
	ID        int64        `json:"id"`
	Name      string       `json:"name"`
	CreatedAt time.Time    `json:"createdAt"`
	UpdatedAt sql.NullTime `json:"updatedAt"`
}

type Tournamentteam struct {
	ID           int64        `json:"id"`
	TeamID       int64        `json:"teamId"`
	TournamentID int64        `json:"tournamentId"`
	IsWinner     sql.NullBool `json:"isWinner"`
	CreatedAt    time.Time    `json:"createdAt"`
	UpdatedAt    sql.NullTime `json:"updatedAt"`
}

type User struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Email     string    `json:"email"`
	Password  string    `json:"-"`
	CreatedAt time.Time `json:"createdAt"`
	UpdatedAt time.Time `json:"updatedAt"`
}
